# Generated by Django 2.0.5 on 2018-06-21 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('comment_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('trade_location', models.CharField(max_length=32)),
                ('price', models.IntegerField(default=0)),
                ('picture_url', models.CharField(blank=True, default='/market/media/goods/default.jpg', max_length=128)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='goods')),
                ('discount', models.IntegerField(blank=True, default=0)),
                ('goods_phone', models.IntegerField(blank=True, null=True)),
                ('goods_qq', models.IntegerField(blank=True, null=True)),
                ('publish_time', models.DateField(auto_now_add=True, null=True)),
                ('seen_times', models.IntegerField(default=0)),
                ('report_times', models.IntegerField(default=0)),
                ('on_sale', models.BooleanField(default=True)),
                ('down_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete='cascade', to='market.Category')),
            ],
        ),
        migrations.CreateModel(
            name='InstationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140)),
                ('send_time', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarkedTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_time', models.DateTimeField(auto_now_add=True)),
                ('goods', models.ForeignKey(on_delete='cascade', to='market.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(blank=True, default='30', editable=False, null=True)),
                ('width', models.PositiveIntegerField(blank=True, default='30', editable=False, null=True)),
                ('avatar', models.ImageField(blank=True, default='profile/default.png', height_field='height', upload_to='profile', width_field='width')),
                ('is_manager', models.BooleanField(default=False)),
                ('date', models.DateField(null=True)),
                ('campus', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete='cascade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='markedtable',
            name='user',
            field=models.ForeignKey(on_delete='cascade', to='market.UserProfile'),
        ),
        migrations.AddField(
            model_name='instationmessage',
            name='receiver',
            field=models.ForeignKey(on_delete='cascade', related_name='receiver_id', to='market.UserProfile'),
        ),
        migrations.AddField(
            model_name='instationmessage',
            name='sender',
            field=models.ForeignKey(on_delete='cascade', related_name='sender_id', to='market.UserProfile'),
        ),
        migrations.AddField(
            model_name='goods',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', to='market.UserProfile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', to='market.Goods'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', to='market.UserProfile'),
        ),
    ]
