# Generated by Django 2.0.5 on 2018-06-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_userprofile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='grade',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
